### ISSUE TITLE
cli로 관리자 생성 안되는 문제

### ISSUE THREAD

**Issue by upgle** [soomtong/blititor#22]
## Scenario

$ node core/setup.js admin
## Error log

B: 관리자 아이디를 입력해주세요... (E-Mail 형태를 사용합니다.):  (admin@blititor.com) admin@upgle.com
 B: Enter administrator password:  *******

info: Access database connection
readline.js:924
            throw err;
            **^**

ReferenceError: BLITITOR is not defined
    at initConnection (/Users/seonghyun/Project/blititor/core/lib/connection.js:11:33)
    at Object.<anonymous> (/Users/seonghyun/Project/blititor/core/lib/connection.js:6:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/seonghyun/Project/blititor/module/account/lib/account.js:9:18)
    at Module._compile (module.js:434:26)
## TO-DO

BLITITOR  constant 가 index 진입지점에만 참조 가능한것을 보입니다.

**Comment by soomtong** [comment]
메뉴얼 좀 더 다듬어서 업로드 하겠습니다.

**Comment by ho1234c** [comment]
#27
