### ISSUE TITLE
마지막에 가입한 유저는 로그인이 안됩니다.

### ISSUE THREAD

**Issue by ho1234c** [soomtong/blititor#31]
마지막에 가입한 유저는 로그인이 안됩니다. DB에는 잘 들어가는데 가져오는 부분에서 문제가 있는것 같습니다.

```
2016/9/25 18:36 [41076] - verbose: Serialize in process for id=9, user_id=ccc@cc
c.com, user_password=$2a$08$Xw3ugYO3kNbdElpm/JovQ.qU1DYfhXGv3d43y9dbrxYh4UhM2egt
S
C:\Users\JongHo\WebstormProjects\blititor\node_modules\mysql-connection-manager\
node_modules\mysql\lib\protocol\Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'uuid' of null
    at C:\Users\JongHo\WebstormProjects\blititor\module\account\lib\passoprt.js:
52:25
    at C:\Users\JongHo\WebstormProjects\blititor\module\account\lib\account.js:2
4:20
    at Query._callback (C:\Users\JongHo\WebstormProjects\blititor\module\account
\lib\database.js:184:16)
    at Query.Sequence.end (C:\Users\JongHo\WebstormProjects\blititor\node_module
s\mysql-connection-manager\node_modules\mysql\lib\protocol\sequences\Sequence.js
:96:24)
    at Query._handleFinalResultPacket (C:\Users\JongHo\WebstormProjects\blititor
\node_modules\mysql-connection-manager\node_modules\mysql\lib\protocol\sequences
\Query.js:144:8)
    at Query.EofPacket (C:\Users\JongHo\WebstormProjects\blititor\node_modules\m
ysql-connection-manager\node_modules\mysql\lib\protocol\sequences\Query.js:128:8
)
    at Protocol._parsePacket (C:\Users\JongHo\WebstormProjects\blititor\node_mod
ules\mysql-connection-manager\node_modules\mysql\lib\protocol\Protocol.js:280:23
)
    at Parser.write (C:\Users\JongHo\WebstormProjects\blititor\node_modules\mysq
l-connection-manager\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\Users\JongHo\WebstormProjects\blititor\node_modules\my
sql-connection-manager\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\JongHo\WebstormProjects\blititor\node_module
s\mysql-connection-manager\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by soomtong** [comment]
역시 직접 고쳐 볼 수 있을 것 같으면 알려주세요!

**Comment by ho1234c** [comment]
로컬에 DB가 꼬여서 그랬던 문제였습니다. 리셋으로 해결했습니다.
