### ISSUE TITLE
동일 Email 로 가입시 Duplicate entry 에러와 함께 App이 죽는 문제

### ISSUE THREAD

**Issue by upgle** [soomtong/blititor#33]
## Environment
- Plain 테마
- MacOS, node v4.1.1
## Scenario
1. Plain 테마 하단에서 가입을 시도.
2. 같은 이메일 주소로 가입
## Error Log

```
2016/9/25 18:49 [59345] - error:  Error: ER_DUP_ENTRY: Duplicate entry 'admin@upgle.com' for key 'auth_user_id_unique'
    at Query.Sequence._packetToError (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    --------------------
    at Protocol._enqueue (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/Connection.js:201:25)
    at Object.insertAuth [as writeAuth] (/Users/seonghyun/Project/blititor/module/account/lib/database.js:248:16)
    at /Users/seonghyun/Project/blititor/module/account/lib/account.js:209:12
/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'insertId' of undefined
    at /Users/seonghyun/Project/blititor/module/account/lib/account.js:219:33
    at Query._callback (/Users/seonghyun/Project/blititor/module/account/lib/database.js:249:9)
    at Query.Sequence.end (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/seonghyun/Project/blititor/node_modules/mysql-connection-manager/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by soomtong** [comment]
직접 수정 해 보 실 수 있겠어요?

**Comment by soomtong** [comment]
`/module/account/lib/account.js` 파일 내에 
- https://github.com/soomtong/blititor/blob/develop/module/account/lib/account.js#L88
- https://github.com/soomtong/blititor/blob/develop/module/account/lib/account.js#L184

두개의 계정 등록 함수가 있는데 이 부분 예외처리가 필요한 상황입니다.

데이터베이스에서 uniq 세팅이 되어 있으니 오류를 내는 것이 당연하죠.
- https://github.com/soomtong/blititor/blob/develop/module/account/lib/database.js#L49

왜 예외를 작성하지 않았습니까? 라고 물으면 '여러분을 위해서...' (방패!!!)
