### ISSUE TITLE
로그인 안하고 채팅 페이지 접근시 앱이 죽어버리는 문제

### ISSUE THREAD

**Issue by upgle** [soomtong/blititor#69]
로그인 안하고 채팅 페이지 접근시 앱이 죽어버리는 문제가 있습니다.

```
/Users/seonghyun/Project/blititor/module/chatting/lib/chatting.js:24
        var uuid = session.passport.user;
                                   ^

TypeError: Cannot read property 'user' of undefined
    at Namespace.<anonymous> (/Users/seonghyun/Project/blititor/module/chatting/lib/chatting.js:24:36)
    at emitOne (events.js:77:13)
    at Namespace.emit (events.js:169:7)
    at Namespace.emit (/Users/seonghyun/Project/blititor/node_modules/socket.io/lib/namespace.js:206:10)
    at /Users/seonghyun/Project/blititor/node_modules/socket.io/lib/namespace.js:174:14
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

```

**Comment by upgle** [comment]
이슈 처리중입니다.

**Comment by upgle** [comment]
@soomtong 이슈 종료합니다~
